/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Language {
  code: string;
  name: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish (Español)" },
  { code: "fr", name: "French (Français)" },
  { code: "de", name: "German (Deutsch)" },
  { code: "it", name: "Italian (Italiano)" },
  { code: "pt", name: "Portuguese (Português)" },
  { code: "ar", name: "Arabic (العربية)" },
  { code: "zh", name: "Chinese (中文)" },
  { code: "ja", name: "Japanese (日本語)" },
  { code: "ru", name: "Russian (Русский)" },
  { code: "nl", name: "Dutch (Nederlands)" },
  { code: "pl", name: "Polish (Polski)" },
  { code: "tr", name: "Turkish (Türkçe)" },
  { code: "sv", name: "Swedish (Svenska)" },
  { code: "id", name: "Indonesian (Bahasa Indonesia)" },
  { code: "uk", name: "Ukrainian (Українська)" },
  { code: "cs", name: "Czech (Čeština)" },
  { code: "da", name: "Danish (Dansk)" },
  { code: "fi", name: "Finnish (Suomi)" },
  { code: "el", name: "Greek (Ελληνικά)" },
  { code: "hi", name: "Hindi (हिन्दी)" },
  { code: "hu", name: "Hungarian (Magyar)" },
  { code: "ko", name: "Korean (한국어)" },
  { code: "no", name: "Norwegian (Norsk)" },
  { code: "ro", name: "Romanian (Română)" },
  { code: "sk", name: "Slovak (Slovenčina)" },
  { code: "th", name: "Thai (ไทย)" },
  { code: "vi", name: "Vietnamese (Tiếng Việt)" },
  { code: "bg", name: "Bulgarian (Български)" },
  { code: "ca", name: "Catalan (Català)" },
  { code: "hr", name: "Croatian (Hrvatski)" },
  { code: "et", name: "Estonian (Eesti)" },
  { code: "he", name: "Hebrew (עברית)" },
  { code: "ga", name: "Irish (Gaeilge)" },
  { code: "lv", name: "Latvian (Latviešu)" },
  { code: "lt", name: "Lithuanian (Lietuvių)" },
  { code: "ms", name: "Malay (Bahasa Melayu)" },
  { code: "mt", name: "Maltese (Malti)" },
  { code: "fa", name: "Persian (فارسی)" },
  { code: "sl", name: "Slovenian (Slovenščina)" },
  { code: "tl", name: "Tagalog (Filipino)" },
  { code: "cy", name: "Welsh (Cymraeg)" },
  { code: "af", name: "Afrikaans" },
  { code: "sq", name: "Albanian (Shqip)" },
  { code: "am", name: "Amharic (አማርኛ)" },
  { code: "hy", name: "Armenian (Հայերեն)" },
  { code: "az", name: "Azerbaijani (Azərbaycanca)" },
  { code: "eu", name: "Basque (Euskara)" },
  { code: "be", name: "Belarusian (Беларуская)" },
  { code: "bn", name: "Bengali (বাংলা)" },
  { code: "bs", name: "Bosnian (Bosanski)" },
  { code: "my", name: "Burmese (မြန်မာ)" },
  { code: "ceb", name: "Cebuano" },
  { code: "co", name: "Corsican (Corsu)" },
  { code: "eo", name: "Esperanto" },
  { code: "gl", name: "Galician (Galego)" },
  { code: "ka", name: "Georgian (ქართული)" },
  { code: "gu", name: "Gujarati (ગુજરાતી)" },
  { code: "ht", name: "Haitian Creole (Kreyòl Ayisyen)" },
  { code: "ha", name: "Hausa" },
  { code: "haw", name: "Hawaiian (ʻŌlelo Hawaiʻi)" },
  { code: "hmn", name: "Hmong (Hmoob)" },
  { code: "is", name: "Icelandic (Íslenska)" },
  { code: "ig", name: "Igbo" },
  { code: "jw", name: "Javanese (Jawa)" },
  { code: "kn", name: "Kannada (ಕನ್ನಡ)" },
  { code: "kk", name: "Kazakh (Қазақ)" },
  { code: "km", name: "Khmer (ខ្មែរ)" },
  { code: "ku", name: "Kurdish (Kurdî)" },
  { code: "ky", name: "Kyrgyz (Кыргызча)" },
  { code: "lo", name: "Lao (ລາວ)" },
  { code: "la", name: "Latin (Latina)" },
  { code: "lb", name: "Luxembourgish (Lëtzebuergesch)" },
  { code: "mk", name: "Macedonian (Македонски)" },
  { code: "mg", name: "Malagasy" },
  { code: "ml", name: "Malayalam (മലയാളം)" },
  { code: "mi", name: "Maori (Māori)" },
  { code: "mr", name: "Marathi (मराठी)" },
  { code: "mn", name: "Mongolian (Монгол)" },
  { code: "ne", name: "Nepali (नेपाली)" },
  { code: "ny", name: "Nyanja (Chichewa)" },
  { code: "or", name: "Odia (ଓଡ଼ିଆ)" },
  { code: "ps", name: "Pashto (پښتو)" },
  { code: "pa", name: "Punjabi (ਪੰਜਾਬੀ)" },
  { code: "sm", name: "Samoan (Gagana Sāmoa)" },
  { code: "gd", name: "Scots Gaelic (Gàidhlig)" },
  { code: "sr", name: "Serbian (Српски)" },
  { code: "st", name: "Sesotho" },
  { code: "sn", name: "Shona (Chishona)" },
  { code: "sd", name: "Sindhi (سنڌي)" },
  { code: "si", name: "Sinhala (සිංහල)" },
  { code: "so", name: "Somali (Soomaali)" },
  { code: "su", name: "Sundanese" },
  { code: "sw", name: "Swahili (Kiswahili)" },
  { code: "tg", name: "Tajik (Тоҷикӣ)" },
  { code: "ta", name: "Tamil (தமிழ்)" },
  { code: "tt", name: "Tatar" },
  { code: "te", name: "Telugu (తెలుగు)" },
  { code: "ug", name: "Uyghur (ئۇيغուրչە)" },
  { code: "uz", name: "Uzbek (Oʻzbek)" },
  { code: "xh", name: "Xhosa (isiXhosa)" },
  { code: "yi", name: "Yiddish (ייִדיש)" },
  { code: "yo", name: "Yoruba (Yorùbá)" },
  { code: "zu", name: "Zulu (isiZulu)" }
];
